/**
 * Welcome to the living style guide.
 *
 * This style guide is loaded with Bootstrap and FontAwesome, so things like
 * <button class="btn btn-default">Default Button</button> and <i class="fa fa-usb"></i> work just fine.
 *
 * Pages and sections are generated by a comment parser, which looks for Javadoc style comments structured according to
 * <a href="https://github.com/straker/livingcss">the livingcss github repo</a>.
 *
 * It makes it easy to show examples of specific cirumstances like
 * @example
 * <div style="color:red">
 *    When to use divs
 * </div>
 * <span style="color:blue">
 *    versus spans.
 * </span>
 *
 * @section Style Guide
 */

/**
 * The style guide can handle infinite nesting of children, and will link to other pages and sections, but not child sections.
 * The project uses Prism and Markdown for highlighting, and currently supports a the following languages:
 *
 * @section Language Highlighting
 * @sectionof Style Guide
 */

/**
 * @code {typescript}
 * let typescript: boolean = true;
 *
 * @section Typescript
 * @sectionof Style Guide.Language Highlighting
 */

/**
 * @code {javascript}
 * var foo = 'bar';
 *
 * @section Javascript
 * @sectionof Style Guide.Language Highlighting
 */

/**
 * @code {css}
 * p {
 *  font-size: 2rem;
 * }
 * @section CSS
 * @sectionof Style Guide.Language Highlighting
 */

/**
 * @code {scss}
 * $primary-color: #333;
 *
 * body {
 * font: 100% $font-stack;
 * color: $primary-color;
 * }
 * @section SCSS
 * @sectionof Style Guide.Language Highlighting
 */

/**
 * @code {json}
 * foo: {
 *  bar: [8,34,16]
 * }
 * @section JSON
 * @sectionof Style Guide.Language Highlighting
 */

/**
 * Feel free to leave feedback in Confluence or the #future-design Slack channel.
 *
 * @section Feedback
 */
